### ISSUE TITLE
E0408 20:28:42.159221 21128 handler.go:59] filter.check_admin_error

### ISSUE THREAD

**Issue by cppfuns** [GUAIK-ORG/gtask#1]
windows 编译OK，运行的话 use test 时报错，看代码执行的http get http://127.0.0.1:1126/task/job?key=test
客户端报的

```
 > use test1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x66768f]

goroutine 1 [running]:
main.(*JobClient).GetJob(0xc000107e80, 0xc000090124, 0x6, 0x0)
        D:/github/go/gtask/client/client.go:58 +0x1bf
main.main()
        D:/github/go/gtask/client/client.go:229 +0x1028
```

服务端报的
`E0408 20:28:42.159221 21128 handler.go:59] filter.check_admin_error`

**Comment by noxrick91** [comment]
windows的编译脚本我没有写在build目录下，filter.check_admin_error这个错误是密钥错误，默认密钥配置文件中：https://github.com/GUAIK-ORG/gtask/blob/master/config/config.json。客户端用windows的方式重新编译应该就可以解决这个报错了。
