### ISSUE TITLE
一个服务端，是否支持多个客户端？

### ISSUE THREAD

**Issue by cppfuns** [GUAIK-ORG/gtask#2]
正在找一个类似的程序，一个服务端可以连接多个客户端，然后后台页面就可以给各个客户端配置任务了

**Comment by noxrick91** [comment]
这个项目支持提交lua运行脚本给服务端，服务端支持lua执行http的请求操作。如果需要服务端给客户端发送请求，那么客户端需要支持http服务，任务系统可以定期的发送post或get请求过去。

**Comment by cppfuns** [comment]
感谢回复，加油
